In [27]:
import pandas as pd
df_crimes = pd.read_csv("/home/wendel/Downloads/tbl_crimes.csv", sep=";", encoding='utf8', low_memory =False)
df_classif = pd.read_csv("/home/wendel/Downloads/tbl_validadores.csv", sep=";", encoding='utf8', low_memory =False)

In [ ]:
def class_setores(row):
    if row['NOME_BAIRRO'] in df_classificadores['VALIDADOR'].values:
        return df_classificadores[
            (df_classificadores['VALIDADOR']==row['NOME_BAIRRO']) &
            (df_classificadores['VALIDADOR_TIPO']=='BAIRRO')
        ]['SETOR'].values[0]
    else:
        'other'

df_crimes['Companhia'] = df_crimes.apply(lambda row: class_setores(row), axis=1)

df_crimes.head(1)

In [42]:
df_crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47436 entries, 0 to 47435
Data columns (total 38 columns):
Número REDS                             47436 non-null object
Órgão Unidade Registro                  47436 non-null object
Unidade Área Militar                    47436 non-null object
Unidade Relato Nível 6                  47436 non-null object
Unid Digitação Nível 6                  47436 non-null object
Unid Registro Nível 6                   47436 non-null object
Código Subclasse Nat Principal          47436 non-null object
Tentado/Consumado Nat Principal         47436 non-null object
Código Subclasse Nat Sec1               47436 non-null object
Tentado/Consumado Nat Sec1              47436 non-null object
Código Subclasse Nat Sec2               47436 non-null object
Tentado/Consumado Nat Sec2              47436 non-null object
Código Subclasse Nat Sec3               47436 non-null object
Tentado/Consumado Nat Sec3              47436 non-null object
ALVO                                    47436 non-null object
Descrição Meio Utilizado                47436 non-null object
Data Comunicação Fato                   47436 non-null object
Horário Comunicação Fato                47092 non-null object
Data Fato                               47436 non-null object
Horário Fato                            47436 non-null object
Data Última Atualização                 47436 non-null object
Logradouro Ocorrência - Tipo            47436 non-null object
Logradouro Ocorrência                   47436 non-null object
Logradouro Ocorrência Não Cadastrado    9238 non-null object
Logradouro Cruzamento                   47436 non-null object
Logradouro Cruzamento Não Cadastrado    23 non-null object
Número Logradouro                       45576 non-null object
Bairro                                  47436 non-null object
Bairro Não Cadastrado                   9336 non-null object
Complemento Endereço                    4447 non-null object
Ponto de Referência                     6419 non-null object
Município                               47436 non-null object
Latitude                                39772 non-null object
Longitude                               39771 non-null object
Matrícula Digitador                     47436 non-null object
Matrícula Relator                       47436 non-null int64
Qtde Ocorrências                        47436 non-null int64
SETOR                                   47436 non-null object
dtypes: int64(2), object(36)
memory usage: 13.8+ MB

In [5]:
df_classificadores.head(3)

,MUNICIPIO,VALIDADOR,VALIDADOR_TIPO,CIA_BASE,BAIRRO,TIPO,SETOR,SUBSETOR,COD_SETOR,OBSERVACAO
0,ARAUJOS,MALAQUIAS,LOGRADOURO,280ª CIA PM,ZONA RURAL,RURAL,ZONA RURAL,ZONA RURAL,60,ZONA RUAL 279ª CIA PM
1,CARMO DO CAJURU,JARDIM ALVORADA,BAIRRO,142ª CIA PM,JARDIM ALVORADA,URBANO,PORTO VELHO,NaN,NaN,NaN
2,CARMO DO CAJURU,CHACARAS BELA VISTA,BAIRRO,142ª CIA PM,CHACARAS BELA VISTA,RURAL,NITEROI,NaN,NaN,AO DOS ESTRELA OESTE CLUBE SEDE CAMPESTRE

In [44]:
def class_setores(row):
    if row['Número REDS'] in df_classif['VALIDADOR'].values:
        return df_classif[df_classif['VALIDADOR']==row['Número REDS']]['SETOR'].values[0]
    elif row['Município'] != 'DIVINOPOLIS':
        return row['Município']
    elif row['Bairro'] in df_classif[df_classif['VALIDADOR_TIPO']=='BAIRRO']['VALIDADOR'].values:
        return df_classif[
            (df_classif['VALIDADOR_TIPO'] == 'BAIRRO') &
            (df_classif['VALIDADOR'] == row['Bairro'])
        ]['SETOR'].values[0]
    else:
        return 'other'

df_crimes['SETOR'] = df_crimes.apply(lambda row: class_setores(row), axis=1)

df_crimes[
    (df_crimes['Bairro'] != 'INVÁLIDO') &
    (df_crimes['Município'] == 'DIVINOPOLIS')
][['Bairro', 'SETOR']]

                        Bairro        SETOR
7673                SANTA INES        other
15600        LAGO DAS ROSEIRAS  PORTO VELHO
15676        LAGO DAS ROSEIRAS  PORTO VELHO
15997        LAGO DAS ROSEIRAS  PORTO VELHO
16449          JARDIM ALVORADA  PORTO VELHO
16518  CHACARAS BELO HORIZONTE  PORTO VELHO
16519  CHACARAS BELO HORIZONTE  PORTO VELHO
16555  CHACARAS BELO HORIZONTE  PORTO VELHO
16556  CHACARAS BELO HORIZONTE  PORTO VELHO
16557  CHACARAS BELO HORIZONTE  PORTO VELHO
16571  CHACARAS BELO HORIZONTE  PORTO VELHO
16572  CHACARAS BELO HORIZONTE  PORTO VELHO
16606  CHACARAS BELO HORIZONTE  PORTO VELHO
16607  CHACARAS BELO HORIZONTE  PORTO VELHO
16608  CHACARAS BELO HORIZONTE  PORTO VELHO
16609  CHACARAS BELO HORIZONTE  PORTO VELHO
16613  CHACARAS BELO HORIZONTE  PORTO VELHO
16628  CHACARAS BELO HORIZONTE  PORTO VELHO
16630  CHACARAS BELO HORIZONTE  PORTO VELHO
16642                 CACHIMBA  PORTO VELHO
16648  CHACARAS BELO HORIZONTE  PORTO VELHO
16658  CHACARAS BELO HORIZONTE  PORTO VELHO
16664  CHACARAS BELO HORIZONTE  PORTO VELHO
16672  CHACARAS BELO HORIZONTE  PORTO VELHO
16677  CHACARAS BELO HORIZONTE  PORTO VELHO
16678  CHACARAS BELO HORIZONTE  PORTO VELHO
16679  CHACARAS BELO HORIZONTE  PORTO VELHO
16685  CHACARAS BELO HORIZONTE  PORTO VELHO
16687  CHACARAS BELO HORIZONTE  PORTO VELHO
16694  CHACARAS BELO HORIZONTE  PORTO VELHO
...                        ...          ...
30858               FLORERMIDA     PLANALTO
31037               SANTA CRUZ     PLANALTO
31040               SANTA CRUZ     PLANALTO
31060               SANTA CRUZ     PLANALTO
31061               SANTA CRUZ     PLANALTO
31073               SANTA CRUZ     PLANALTO
31109               SANTA CRUZ     PLANALTO
31144               SANTA CRUZ     PLANALTO
31146               SANTA CRUZ     PLANALTO
31189               SANTA CRUZ     PLANALTO
31192               SANTA CRUZ     PLANALTO
31212               SANTA CRUZ     PLANALTO
31226               SANTA CRUZ     PLANALTO
31280               SANTA CRUZ     PLANALTO
31299               SANTA CRUZ     PLANALTO
31323               SANTA CRUZ     PLANALTO
31350               SANTA CRUZ     PLANALTO
31362               SANTA CRUZ     PLANALTO
31366               SANTA CRUZ     PLANALTO
31367               SANTA CRUZ     PLANALTO
31371               SANTA CRUZ     PLANALTO
31396               SANTA CRUZ     PLANALTO
31397               SANTA CRUZ     PLANALTO
31436               SANTA CRUZ     PLANALTO
31437               SANTA CRUZ     PLANALTO
31491               SANTA CRUZ     PLANALTO
31555               SANTA CRUZ     PLANALTO
31557               SANTA CRUZ     PLANALTO
31602               SANTA CRUZ     PLANALTO
31711               SANTA CRUZ     PLANALTO

[11162 rows x 2 columns]